version: "3.9"

services:
  main-frontend:
    container_name: main-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80

  main-backend-discovery:
    container_name: main-backend-discovery
    build:
      context: ./backend/discovery-server
      dockerfile: Dockerfile
      args:
        SERVER_MODE: main
    ports:
      - 6471:8761
    environment:
      - TZ=Asia/Seoul
    networks:
      - main_hikingdom_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 5s

  main-backend-service:
    container_name: main-backend-service
    build:
      context: ./backend/service
      dockerfile: Dockerfile
      args:
        SERVER_MODE: main
    ports:
      - 8001:8080
    environment:
      - TZ=Asia/Seoul
      - EUREKA_SERVER=main-backend-discovery
    networks:
      - main_hikingdom_net
    depends_on:
      main-backend-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/members/auth/health-check"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  main-backend-chat:
    container_name: main-backend-chat
    build:
      context: ./backend/chat
      dockerfile: Dockerfile
      args:
        SERVER_MODE: main
    ports:
      - 8002:8080
    environment:
      - TZ=Asia/Seoul
      - EUREKA_SERVER=main-backend-discovery
    networks:
      - main_hikingdom_net
    depends_on:
      main-backend-discovery:
        condition: service_healthy

  main-backend-hiking:
    container_name: main-backend-hiking
    build:
      context: ./backend/hiking
      dockerfile: Dockerfile
    ports:
      - 8003:3000
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=main-backend-discovery
    networks:
      - main_hikingdom_net
    depends_on:
      main-backend-discovery:
        condition: service_healthy

  main-backend-gateway:
    container_name: main-backend-gateway
    build:
      context: ./backend/gateway-server
      dockerfile: Dockerfile
      args:
        SERVER_MODE: main
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - EUREKA_SERVER=main-backend-discovery
    networks:
      - main_hikingdom_net
    depends_on:
      main-backend-discovery:
        condition: service_healthy
      main-backend-service:
        condition: service_healthy

  nginx:
    container_name: nginx
    build:
      context: ./.nginx
      dockerfile: Dockerfile
    volumes:
      - ./.nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - main-backend-gateway
      - main-frontend

networks:
  main_hikingdom_net:
    driver: bridge
